#!/bin/bash
echo "🚀 Deployment Checklist for Personal Growth Ecosystem"
echo "====================================================="
echo ""
echo "✅ 1. GitHub Repository Created"
echo "   - Go to: https://github.com/N4rcy/personal-growth-ecosystem"
echo ""
echo "✅ 2. Local Git Setup"
echo "   - git init"
echo "   - git add ."
echo "   - git commit -m 'Initial commit'"
echo "   - git remote add origin https://github.com/N4rcy/personal-growth-ecosystem.git"
echo "   - git push -u origin main"
echo ""
echo "✅ 3. Dependencies Installed"
echo "   - npm install"
echo "   - npm install --save-dev gh-pages"
echo ""
echo "✅ 4. Configuration Files"
echo "   - package.json ✓"
echo "   - vite.config.js ✓"
echo "   - .gitignore ✓"
echo "   - .env.local (with your DeepSeek API key) ✓"
echo ""
echo "✅ 5. Test Locally"
echo "   - npm run dev"
echo "   - Visit: http://localhost:5173"
echo ""
echo "✅ 6. Build & Deploy"
echo "   - npm run build"
echo "   - npm run deploy"
echo ""
echo "✅ 7. Enable GitHub Pages"
echo "   - Go to Repository Settings → Pages"
echo "   - Source: Deploy from a branch"
echo "   - Branch: gh-pages, folder: / (root)"
echo ""
echo "🌐 Your live site will be at:"
echo "   https://N4rcy.github.io/personal-growth-ecosystem"
